### ISSUE TITLE
Changes for galene-0.4

### ISSUE THREAD

**Issue by jech** [erdnaxe/galene-rtmp#5]
Galene-0.4 will change the protocol slightly.  In the case of galene-stream, the only change required will be the following change in the `offer` message: instead of
```
labels: whatever
```
you will need to send
```
label: "camera"
```

I will keep this issue updated if there are any further changes to the protocol.

**Comment by erdnaxe** [comment]
Thank you for the notification. I will apply the fix in a new develop branch then update Galene-stream PyPI package as soon as Galene-0.4 is released.

> The field `label` is one of `camera`, `screenshare` or `video`, and will be matched against the keys sent by the receiver in their `request` message.
> -- https://github.com/jech/galene/blob/master/README.PROTOCOL

Are you sure that Galene-stream should put `"camera"` as a label rather than `"screenshare"` or `"video"`?

**Comment by jech** [comment]
The label is transmitted to the receiver without interpretation by the server.  The receiver decides which labels it wishes to receive.  The current client receives either everything ("Receive: everything") or just the stream labbelled "screenshare" ("Receive: screenshare").

So I think you may choose anything as long as it's not "screenshare".  Perhaps you should pick a new label, specific to galene-stream?

**Comment by erdnaxe** [comment]
Latest tagged version works with Galene-0.4 (almost 4 months late, oops). Thank you!
